#sudo permission
sudo: required
services:
# install the copy of docker
  - docker

before_install: #before the test is ran.
  - docker build -t simon/docker-react -f Dockerfile.dev .

script:
  - docker run simon/docker-react npm run test -- --coverage
