#sudo permission
sudo: required
services:
# install the copy of docker
  - docker

before_install: #before the test is ran.
  - docker build -t simon/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true simon/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"